name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - master # run on push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or your project node version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build Angular App
      - name: Build Angular
        run: npm run build # your ng build command

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GH Pages
        uses: angular-schule/[email protected]
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-href: /
          build-dir: dist/portfolio/browser
          branch: gh-pages
